"""Names for the audit screens: what each audited table holds, and its columns. Columns not
listed fall back to the field's own name."""

from django.utils.translation import gettext_lazy as _

TABLES = {
    "catalog_currency": _("Currency"),
    "catalog_karat": _("Karat"),
    "catalog_itemcategory": _("Category"),
    "catalog_categorymakingcharge": _("Category making charge"),
    "pricing_fxrate": _("Exchange rate"),
    "pricing_metalpriceboard": _("Gold price board"),
    "pricing_metalpriceboardline": _("Gold price"),
    "parties_party": _("Customer or supplier"),
    "parties_partyrole": _("Account role"),
    "parties_customerprofile": _("Customer details"),
    "parties_supplierprofile": _("Supplier details"),
    "org_tenantprofile": _("Company"),
    "org_branch": _("Branch"),
    "iam_membership": _("User"),
    "iam_role": _("Role"),
    "iam_rolepermission": _("Role permission"),
    "iam_membershiprole": _("User role"),
    "iam_membershiprolebranch": _("User role branch"),
    "iam_membershiplimit": _("User limit"),
    "treasury_cashbox": _("Cash box"),
    "treasury_bankaccount": _("Bank account"),
    "treasury_bankaccountbranch": _("Bank account branch"),
    "treasury_cardterminal": _("Card terminal"),
    "ledger_account": _("Ledger account"),
    "hr_employee": _("Employee"),
    "expenses_expensecategory": _("Expense category"),
    "printing_labeltemplate": _("Label template"),
    "printing_documentdesign": _("Document design"),
    "inventory_item": _("Piece"),
    "diamonds_itemstone": _("Stone details"),
}

COLUMNS = {
    "name": _("Name"), "code": _("Code"), "is_active": _("Active"), "phone": _("Phone"),
    "alt_phone": _("Other phone"), "email": _("Email"), "address": _("Address"),
    "notes": _("Notes"), "note": _("Note"), "kind": _("Kind"),
    "national_id_encrypted": _("National ID"), "national_id_hash": _("National ID"),
    "home_branch_id": _("Branch"), "branch_id": _("Branch"), "role": _("Role"),
    "role_id": _("Role"), "user_id": _("User"), "username": _("Username"), "status": _("Status"),
    "default_branch_id": _("Default branch"), "permission": _("Permission"),
    "all_branches": _("All branches"), "currency_id": _("Currency"), "account_id": _("Account"),
    "bank_name": _("Bank"), "account_number": _("Account number"), "iban": _("IBAN"),
    "fee_rate": _("Fee"), "is_default": _("Default"), "symbol": _("Symbol"),
    "minor_units": _("Decimals"), "fineness": _("Fineness"), "display_name": _("Display name"),
    "metal_id": _("Metal"), "karat_id": _("Karat"), "category_id": _("Category"),
    "parent_id": _("Parent"), "commission_rate": _("Commission"),
    "cost_rate_per_g": _("Making cost / g"), "list_rate_per_g": _("Sale making / g"),
    "rate": _("Rate"), "effective_at": _("Effective from"), "source": _("Source"),
    "sell_price_per_g": _("Sell price / g"), "buy_price_per_g": _("Buy price / g"),
    "scrap_buy_price_per_g": _("Scrap buy price / g"), "board_id": _("Price board"),
    "party_id": _("Account"), "legal_name": _("Legal name"),
    "tax_registration_no": _("Tax registration no."), "whatsapp_number": _("WhatsApp"),
    "logo": _("Logo"), "accent": _("Accent colour"), "is_head_office": _("Head office"),
    "job_title": _("Job"), "hired_on": _("Hired on"), "monthly_salary": _("Monthly salary"),
    "commission_basis": _("Commission"), "type": _("Type"), "is_postable": _("Postable"),
    "barcode": _("Barcode"), "gross_weight_g": _("Weight (g)"),
    "fine_weight_g": _("Fine gold"), "cost_making_rate": _("Making cost / g"),
    "cost_amount": _("Cost"), "list_making_rate": _("Sale making / g"),
    "label_price": _("Label price"), "supplier_id": _("Supplier"),
    "stone_weight_ct": _("Stones (ct)"), "stone_cost_amount": _("Stones' cost"),
    "carat": _("Carats"), "clarity": _("Clarity"), "certificate_no": _("Certificate no."),
    "lab": _("Lab"), "cut": _("Cut"), "count": _("Count"), "item_id": _("Piece"),
    "description": _("Description"), "value": _("Value"),
    "key": _("Limit"), "membership_id": _("User"), "short_name": _("Short name"),
}
