# Generated by Django 5.2.17 on 2026-09-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('org', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'username'), name='iam_membership_username_uniq'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='iam_membership_user_uniq'),
        ),
    ]
