# Generated by Django 5.2.17 on 2026-09-28 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('ledger', '0005_account_commodity'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('pricing', '0002_rls'),
        ('purchasing', '0002_rls'),
        ('tenants', '0001_initial'),
        ('treasury', '0003_holders_for_existing_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('seller_phone', models.CharField(blank=True, max_length=30)),
                ('seller_id_encrypted', models.TextField(blank=True)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('account', 'On their account')], max_length=16)),
                ('total_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('total_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.metalpriceboard')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('loss_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('net_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price_overridden', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.scrappurchase')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('account', 'On their account')], max_length=16)),
                ('total_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('total_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.scrapsale')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='scrappurchase',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='scrap_purchase_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrappurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='purchasing_scrappurchase_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scrappurchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('net_weight_g__gt', 0)), name='scrap_purchase_line_check'),
        ),
        migrations.AddIndex(
            model_name='scrapsale',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='scrap_sale_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrapsale',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='purchasing_scrapsale_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scrapsaleline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('gross_weight_g__gt', 0)), name='scrap_sale_line_check'),
        ),
    ]
