# Generated by Django 5.2.17 on 2026-09-28 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('purchasing', '0004_rls_scrap'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scrappurchaseline',
            index=models.Index(fields=['tenant', 'purchase'], name='scrap_purchase_line_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapsaleline',
            index=models.Index(fields=['tenant', 'sale'], name='scrap_sale_line_idx'),
        ),
    ]
