# Generated by Django 5.2.17 on 2026-09-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_rls_supplier_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='seller_role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('trade_account', 'Trade account')], default='supplier', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='seller_role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('trade_account', 'Trade account')], default='supplier', max_length=16),
        ),
    ]
