# Generated by Django 5.2.17 on 2026-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_seller_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoicepiece',
            name='label_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoicepiece',
            name='stone_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoicepiece',
            name='stone_weight_ct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoicepiece',
            name='stones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
