# Generated by Django 5.2.17 on 2026-09-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0002_rls_and_append_only'),
        ('ledger', '0004_metal_position_account'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('pricing', '0002_rls'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash'), ('credit', 'On account')], default='cash', max_length=8)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trade_in_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.metalpriceboard')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('metal_price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('making_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('making_rate_net', models.DecimalField(decimal_places=4, max_digits=18)),
                ('metal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('making_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metal_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('functional_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesTradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('loss_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('net_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price_overridden', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_ins', to='sales.salesinvoice')),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='sales_invoice_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='sales_salesinvoice_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice', 'position'), name='sales_line_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_rate__gte', 0), ('discount_rate__lte', 1)), name='sales_line_discount_check'),
        ),
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['tenant', 'invoice'], name='sales_payment_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='salespayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_positive_check'),
        ),
        migrations.AddIndex(
            model_name='salestradein',
            index=models.Index(fields=['tenant', 'invoice'], name='sales_tradein_invoice_idx'),
        ),
    ]
