# Generated by Django 5.2.17 on 2026-09-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rls_returns'),
        ('treasury', '0003_holders_for_existing_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cardterminal'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox'),
        ),
    ]
