# Generated by Django 5.2.17 on 2026-09-28 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0004_rls_transfers_and_stocktakes'),
        ('ledger', '0005_account_commodity'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('pricing', '0002_rls'),
        ('sales', '0005_salespayment_bank_account_salespayment_cash_box_and_more'),
        ('tenants', '0001_initial'),
        ('treasury', '0003_holders_for_existing_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespayment',
            name='kind',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('deposit', 'Reservation deposit')], max_length=16),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('price_locked', models.BooleanField(default=False)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('quoted_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('cancel_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.metalpriceboard')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='sales.salesinvoice')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('business_date', models.DateField()),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('deposit', 'Reservation deposit')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('functional_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount')),
                ('cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='sales.reservation')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cardterminal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('quoted_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.reservation')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='reservation_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'customer'], name='reservation_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='sales_reservation_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='reservationdeposit',
            index=models.Index(fields=['tenant', 'reservation'], name='reservation_deposit_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationdeposit',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='reservation_deposit_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reservationline',
            constraint=models.UniqueConstraint(fields=('tenant', 'reservation', 'item'), name='reservation_line_item_uniq'),
        ),
    ]
