# Generated by Django 5.2.17 on 2026-09-29 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0004_rls_transfers_and_stocktakes'),
        ('sales', '0007_rls_reservations'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklot'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('lot__isnull', True)), models.Q(('item__isnull', True), ('lot__isnull', False)), _connector='OR'), name='sales_line_item_xor_lot_check'),
        ),
    ]
