# Generated by Django 5.2.17 on 2026-09-29 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0005_trade'),
        ('ledger', '0006_period_status_label'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('pricing', '0002_rls'),
        ('sales', '0009_backfill_line_category'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('settlement_basis', models.CharField(choices=[('metal', 'In gold'), ('money', 'In money')], max_length=8)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('total_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('metal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('making_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.metalpriceboard')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('total_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('total_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.tradesale')),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=1)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('metal_price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('making_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('metal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('making_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metal_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklot')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('trade_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.tradesale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TradeReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('trade_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.tradereturn')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.tradesaleline')),
            ],
        ),
        migrations.AddIndex(
            model_name='tradesale',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='trade_sale_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesale',
            index=models.Index(fields=['tenant', 'trade_account'], name='trade_sale_party_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradesale',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='sales_tradesale_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='tradereturn',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='trade_return_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tradereturn',
            index=models.Index(fields=['tenant', 'original_sale'], name='trade_return_sale_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradereturn',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='sales_tradereturn_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='tradesaleline',
            index=models.Index(fields=['tenant', 'trade_sale'], name='trade_sale_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradesaleline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('lot__isnull', True)), models.Q(('item__isnull', True), ('lot__isnull', False)), _connector='OR'), name='trade_sale_line_xor_check'),
        ),
        migrations.AddConstraint(
            model_name='tradesaleline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_g__gt', 0), ('making_rate__gte', 0)), name='trade_sale_line_values_check'),
        ),
        migrations.AddIndex(
            model_name='tradereturnline',
            index=models.Index(fields=['tenant', 'trade_return'], name='trade_returnline_idx'),
        ),
        migrations.AddIndex(
            model_name='tradereturnline',
            index=models.Index(fields=['tenant', 'original_line'], name='trade_returnline_orig_idx'),
        ),
    ]
