# Generated by Django 5.2.17 on 2026-10-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('sales', '0011_rls_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='stone_cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='stones_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='karat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat'),
        ),
    ]
