# Generated by Django 5.2.17 on 2026-10-06 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_item_stone_cost_amount'),
        ('ledger', '0013_cash_over_short'),
        ('org', '0006_drop_branch_diamonds_flag'),
        ('parties', '0004_workshop_permissions'),
        ('tenants', '0006_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('gross_before_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('gross_after_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stones_carat', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stones_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labour_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoneSettingStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carat', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='diamonds.stonesetting')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('pearl', 'Pearl'), ('other', 'Other stone')], default='diamond', max_length=12)),
                ('shape', models.CharField(blank=True, choices=[('round', 'Round'), ('princess', 'Princess'), ('oval', 'Oval'), ('pear', 'Pear'), ('marquise', 'Marquise'), ('emerald_cut', 'Emerald cut'), ('cushion', 'Cushion'), ('heart', 'Heart'), ('baguette', 'Baguette'), ('other', 'Other shape')], max_length=12)),
                ('count', models.PositiveIntegerField(default=1)),
                ('carat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('clarity', models.CharField(blank=True, max_length=20)),
                ('cut', models.CharField(blank=True, max_length=20)),
                ('lab', models.CharField(blank=True, max_length=40)),
                ('certificate_no', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='inventory.item')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-carat', 'id'],
                'indexes': [models.Index(fields=['tenant', 'item'], name='diamonds_stone_item_idx'), models.Index(fields=['tenant', 'certificate_no'], name='diamonds_stone_cert_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('carat__gt', 0), ('count__gte', 1)), name='diamonds_stone_values_check')],
            },
        ),
        migrations.AddIndex(
            model_name='stonesetting',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='diamonds_setting_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='stonesetting',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='diamonds_stonesetting_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stonesettingstone',
            constraint=models.UniqueConstraint(fields=('tenant', 'setting', 'stone'), name='diamonds_setting_stone_uniq'),
        ),
    ]
