# Generated by Django 5.2.17 on 2026-10-06 16:17

import django.db.models.deletion
from django.db import migrations, models

from apps.audit.triggers import GuardTenantFKs


class Migration(migrations.Migration):

    dependencies = [
        ('diamonds', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstone',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='diamonds.stonesetting'),
        ),
        GuardTenantFKs("ItemStone"),
    ]
