# Generated by Django 5.2.17 on 2026-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonds', '0004_grant_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstone',
            name='kind',
            field=models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald (gem)'), ('sapphire', 'Sapphire'), ('pearl', 'Pearl'), ('other', 'Other stone')], default='diamond', max_length=12),
        ),
    ]
