# Generated by Django 5.2.17 on 2026-09-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPriceBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference_karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetalPriceBoardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sell_price_per_g', models.DecimalField(decimal_places=4, max_digits=18)),
                ('buy_price_per_g', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('scrap_buy_price_per_g', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('is_derived', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.metalpriceboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('effective_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'currency', '-effective_at'], name='pricing_fxrate_current_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='pricing_fxrate_positive_check')],
            },
        ),
        migrations.AddIndex(
            model_name='metalpriceboard',
            index=models.Index(fields=['tenant', '-effective_at'], name='pricing_board_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='metalpriceboardline',
            constraint=models.UniqueConstraint(fields=('tenant', 'board', 'karat'), name='pricing_boardline_karat_uniq'),
        ),
        migrations.AddConstraint(
            model_name='metalpriceboardline',
            constraint=models.CheckConstraint(condition=models.Q(('sell_price_per_g__gt', 0), models.Q(('buy_price_per_g__isnull', True), ('buy_price_per_g__gt', 0), _connector='OR'), models.Q(('scrap_buy_price_per_g__isnull', True), ('scrap_buy_price_per_g__gt', 0), _connector='OR')), name='pricing_boardline_positive_check'),
        ),
    ]
