# Generated by Django 5.2.17 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('collector', 'Collector'), ('page', 'Page')], default='collector', max_length=10)),
                ('host', models.CharField(blank=True, max_length=120)),
                ('cpu_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('load_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('mem_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('mem_used', models.BigIntegerField()),
                ('mem_total', models.BigIntegerField()),
                ('swap_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('disk_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('disk_used', models.BigIntegerField()),
                ('disk_total', models.BigIntegerField()),
                ('net_sent', models.BigIntegerField(default=0)),
                ('net_recv', models.BigIntegerField(default=0)),
                ('io_read', models.BigIntegerField(default=0)),
                ('io_write', models.BigIntegerField(default=0)),
                ('net_out_bps', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('net_in_bps', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('io_read_bps', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('io_write_bps', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('process_rss', models.BigIntegerField(blank=True, null=True)),
                ('db_size', models.BigIntegerField(blank=True, null=True)),
                ('db_connections', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
