# Generated by Django 5.2.17 on 2026-09-24 11:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$', 'Lowercase letters, digits and hyphens; must start and end with a letter or digit.')])),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('migrating', 'Migrating'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('purged', 'Purged')], default='provisioning', max_length=16)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='tenants_tenantdomain_one_primary_uniq'), models.CheckConstraint(condition=models.Q(('domain', django.db.models.functions.text.Lower('domain'))), name='tenants_tenantdomain_lowercase_check')],
            },
        ),
    ]
