# Generated by Django 5.2.17 on 2026-10-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='requests_per_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantRouteTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('route', models.CharField(max_length=200)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('slow', models.PositiveIntegerField(default=0)),
                ('total_ms', models.BigIntegerField(default=0)),
                ('max_ms', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['day'], name='tenants_route_traffic_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day', 'route'), name='tenants_route_traffic_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TenantTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField()),
                ('requests', models.PositiveIntegerField(default=0)),
                ('throttled', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('slow', models.PositiveIntegerField(default=0)),
                ('total_ms', models.BigIntegerField(default=0)),
                ('max_ms', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['minute'], name='tenants_traffic_minute_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'minute'), name='tenants_traffic_minute_uniq')],
            },
        ),
    ]
