# Generated by Django 5.2.17 on 2026-10-03 14:25

import apps.core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Gweb', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('logo', models.FileField(blank=True, upload_to=apps.core.media.PlatformUploadPath('branding'), validators=[apps.core.media.validate_image])),
                ('logo_dark', models.FileField(blank=True, upload_to=apps.core.media.PlatformUploadPath('branding'), validators=[apps.core.media.validate_image])),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform settings',
            },
        ),
    ]
