# Generated by Django 5.2.17 on 2026-10-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=16)),
                ('key', models.CharField(max_length=40)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='tenants_planfeature_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='tenants_tenantfeature_uniq')],
            },
        ),
    ]
