# Generated by Django 5.2.17 on 2026-10-03 18:18

import apps.platform.tenants.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# The plans that used to be fixed in code, kept as they were so no client changes.
PLANS = [
    ("trial", "Trial", "تجريبي", 0),
    ("standard", "Standard", "قياسية", 1),
    ("professional", "Professional", "احترافية", 2),
    ("enterprise", "Enterprise", "مؤسسية", 3),
]


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("tenants", "Plan")
    Tenant = apps.get_model("tenants", "Tenant")
    PlanFeature = apps.get_model("tenants", "PlanFeature")
    db = schema_editor.connection.alias
    for code, name, name_ar, position in PLANS:
        Plan.objects.using(db).get_or_create(code=code, defaults={
            "name": name, "name_ar": name_ar, "position": position,
            "is_default": code == "standard"})
    # Any other value already stored gets a plan of its own rather than breaking the link.
    used = set(Tenant.objects.using(db).values_list("plan", flat=True))
    used |= set(PlanFeature.objects.using(db).values_list("plan", flat=True))
    for position, code in enumerate(sorted(used - {c for c, *_ in PLANS}), start=len(PLANS)):
        Plan.objects.using(db).create(code=code, name=code.title(), position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$', 'Lowercase letters, digits and hyphens.')])),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=8)),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('requests_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='tenants_plan_one_default_uniq')],
            },
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.CASCADE, related_name='feature_rows', to='tenants.plan', to_field='code'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(db_column='plan', default=apps.platform.tenants.models.default_plan_code, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.plan', to_field='code'),
        ),
    ]
