# Generated by Django 5.2.17 on 2026-09-28 11:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('media', models.CharField(choices=[('roll', 'Roll (one label at a time)'), ('sheet', 'Sheet (several labels per page)')], default='roll', max_length=8)),
                ('layout', models.CharField(choices=[('single', 'One area'), ('split', 'Two wings (jewellery tail tag)')], default='single', max_length=8)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tail_mm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fields', models.JSONField(default=list)),
                ('fields_b', models.JSONField(blank=True, default=list)),
                ('font_size_pt', models.DecimalField(decimal_places=1, default=Decimal('6'), max_digits=4)),
                ('barcode_height_mm', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5)),
                ('page_width_mm', models.DecimalField(decimal_places=2, default=Decimal('210'), max_digits=6)),
                ('page_height_mm', models.DecimalField(decimal_places=2, default=Decimal('297'), max_digits=6)),
                ('columns', models.PositiveSmallIntegerField(default=1)),
                ('rows', models.PositiveSmallIntegerField(default=1)),
                ('margin_top_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margin_start_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gap_x_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gap_y_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='printing_label_name_uniq'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='printing_label_one_default_uniq'), models.CheckConstraint(condition=models.Q(('columns__gte', 1), ('font_size_pt__gt', 0), ('height_mm__gt', 0), ('rows__gte', 1), ('tail_mm__gte', 0), ('width_mm__gt', 0)), name='printing_label_size_check')],
            },
        ),
    ]
