# Generated by Django 5.2.17 on 2026-10-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.core.tenancy.rls import EnableTenantRLS


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_rls'),
        ('tenants', '0006_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=40)),
                ('layout', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('thermal', 'Thermal slip (80 mm)')], default='classic', max_length=12)),
                ('paper', models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('roll80', '80 mm roll')], default='a4', max_length=8)),
                ('lang', models.CharField(blank=True, choices=[('', 'The workspace language'), ('ar', 'Arabic'), ('en', 'English'), ('both', 'Arabic and English')], default='', max_length=4)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('show_logo', models.BooleanField(default=True)),
                ('header_note', models.CharField(blank=True, max_length=300)),
                ('footer_note', models.CharField(blank=True, max_length=300)),
                ('terms', models.TextField(blank=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('custom_html', models.TextField(blank=True)),
                ('use_custom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_html', models.TextField()),
                ('saved_by', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='printing.documentdesign')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentdesign',
            constraint=models.UniqueConstraint(fields=('tenant', 'doc_type'), name='printing_documentdesign_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='documentdesignversion',
            index=models.Index(fields=['tenant', 'design'], name='printing_docver_design_idx'),
        ),
        EnableTenantRLS("DocumentDesign"),
        EnableTenantRLS("DocumentDesignVersion"),
    ]
