# Generated by Django 5.2.17 on 2026-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_document_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdesign',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentdesign',
            name='page',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='documentdesign',
            name='layout',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('thermal', 'Thermal slip (80 mm)'), ('builder', 'My design (designer)')], default='classic', max_length=12),
        ),
    ]
