# Generated by Django 5.2.17 on 2026-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdesign',
            name='follows',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
