# Generated by Django 5.2.17 on 2026-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=16)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('prefix', models.CharField(max_length=8)),
                ('next_value', models.BigIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
            ],
        ),
    ]
