# Generated by Django 5.2.17 on 2026-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rls_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='doc_type',
            field=models.CharField(max_length=40),
        ),
    ]
