# Generated by Django 5.2.17 on 2026-09-24 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=32)),
                ('rfid_epc', models.CharField(blank=True, max_length=24)),
                ('external_code', models.CharField(blank=True, max_length=64)),
                ('item_type', models.CharField(choices=[('gold_piece', 'Gold piece'), ('silver_piece', 'Silver piece'), ('diamond_piece', 'Diamond piece'), ('stone', 'Stone'), ('bullion', 'Bullion'), ('coin', 'Coin'), ('other', 'Other')], max_length=16)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('metal_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('stone_weight_ct', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('in_transit', 'In transit'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('at_workshop', 'At workshop'), ('consumed', 'Used in another piece'), ('returned_to_supplier', 'Returned to supplier'), ('scrapped', 'Scrapped'), ('missing', 'Missing'), ('voided', 'Cancelled')], default='in_stock', max_length=24)),
                ('cost_making_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('list_making_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('label_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemcategory')),
                ('cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='inventory.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_receipt', 'Purchase'), ('purchase_void', 'Purchase cancelled'), ('sale', 'Sale'), ('sale_return', 'Customer return'), ('supplier_return', 'Returned to supplier'), ('transfer_out', 'Sent to branch'), ('transfer_in', 'Received from branch'), ('workshop_issue', 'Sent to workshop'), ('workshop_receipt', 'Back from workshop'), ('production_consume', 'Used in production'), ('production_output', 'Produced'), ('stocktake_adjust', 'Stocktake adjustment'), ('scrap_in', 'Scrap received'), ('scrap_out', 'Scrap out'), ('loss', 'Loss'), ('gain', 'Gain'), ('opening', 'Opening stock')], max_length=24)),
                ('qty', models.IntegerField()),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('document_type', models.CharField(blank=True, max_length=60)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('business_date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'branch', 'status', 'category'], name='inventory_item_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'external_code'], name='inventory_item_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='inventory_item_barcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('rfid_epc', ''), _negated=True), fields=('tenant', 'rfid_epc'), name='inventory_item_rfid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('fine_weight_g__gte', 0), ('gross_weight_g__gte', 0), ('metal_weight_g__gte', 0), ('stone_weight_ct__gte', 0)), name='inventory_item_weights_check'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('tenant', 'category', 'karat', 'branch'), name='inventory_stocklot_key_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'lot'), name='inventory_lotbalance_lot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.CheckConstraint(condition=models.Q(('fine_weight_g__gte', 0), ('gross_weight_g__gte', 0), ('qty__gte', 0)), name='inventory_lotbalance_non_negative_check'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'branch', 'business_date'], name='inventory_movement_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'document_type', 'document_id'], name='inventory_movement_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('lot__isnull', True)), models.Q(('item__isnull', True), ('lot__isnull', False)), _connector='OR'), name='inventory_movement_item_xor_lot_check'),
        ),
    ]
