# Generated by Django 5.2.17 on 2026-09-24 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0002_rls_and_append_only'),
        ('ledger', '0005_account_commodity'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=64)),
                ('expected', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('pending', 'Not counted yet'), ('counted', 'Counted'), ('missing', 'Missing'), ('unexpected', 'Not expected here'), ('left', 'Left during the count')], default='pending', max_length=12)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted', models.BooleanField(default=False)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_qty', models.IntegerField(default=0)),
                ('expected_gross_weight_g', models.DecimalField(decimal_places=3, max_digits=16)),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('counted_gross_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('adjustment_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklot')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_lines', to='inventory.stocktake')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('total_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receive_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metal_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='stocktake_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='inventory_stocktake_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('tenant', 'branch'), name='stocktake_one_open_uniq'),
        ),
        migrations.AddIndex(
            model_name='stocktakeline',
            index=models.Index(fields=['tenant', 'stocktake', 'result'], name='stocktake_line_result_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.UniqueConstraint(fields=('tenant', 'stocktake', 'barcode'), name='stocktake_line_barcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocktakelotline',
            constraint=models.UniqueConstraint(fields=('tenant', 'stocktake', 'lot'), name='stocktake_lot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stocktakelotline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_gross_weight_g__gte', 0), ('counted_gross_weight_g__isnull', True), _connector='OR'), name='stocktake_lot_counted_check'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='stock_transfer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(condition=models.Q(('received_at__isnull', True)), fields=['tenant', 'to_branch'], name='stock_transfer_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='inventory_stocktransfer_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='stocktransferline',
            index=models.Index(fields=['tenant', 'transfer'], name='stock_transfer_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_g__gt', 0), ('qty__gte', 0)), name='stock_transfer_line_check'),
        ),
    ]
