# Generated by Django 5.2.17 on 2026-09-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rls_transfers_and_stocktakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase'), ('purchase_void', 'Purchase cancelled'), ('sale', 'Sale'), ('sale_return', 'Customer return'), ('trade_sale', 'Wholesale'), ('trade_return', 'Wholesale return'), ('supplier_return', 'Returned to supplier'), ('transfer_out', 'Sent to branch'), ('transfer_in', 'Received from branch'), ('workshop_issue', 'Sent to workshop'), ('workshop_receipt', 'Back from workshop'), ('production_consume', 'Used in production'), ('production_output', 'Produced'), ('stocktake_adjust', 'Stocktake adjustment'), ('scrap_in', 'Scrap received'), ('scrap_out', 'Scrap out'), ('loss', 'Loss'), ('gain', 'Gain'), ('opening', 'Opening stock')], max_length=24),
        ),
    ]
