# Generated by Django 5.2.17 on 2026-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stone_cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
