# Generated by Django 5.2.17 on 2026-09-30 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('inventory', '0005_trade'),
        ('ledger', '0006_period_status_label'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0004_workshop_permissions'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('manufacture', 'Making pieces'), ('casting', 'Casting'), ('repair', 'Repair and polishing')], default='manufacture', max_length=12)),
                ('issued_gross_weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('issued_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('carried_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('received_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('loss_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('gain_fine_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('labour_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('receipt_note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receive_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metal_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklot')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_lines', to='manufacturing.workorder')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('pieces', 'New pieces'), ('bulk', 'Gold by weight'), ('scrap', 'Scrap back')], max_length=8)),
                ('qty', models.IntegerField(default=0)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fine_weight_g', models.DecimalField(decimal_places=4, max_digits=16)),
                ('labour_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('labour_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('list_making_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metal_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('karat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='manufacturing.workorder')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='manufacturing.workorderreceiptline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='work_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'workshop'], name='work_order_workshop_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='manufacturing_workorder_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='workorderissueline',
            index=models.Index(fields=['tenant', 'order'], name='work_order_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderissueline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_g__gt', 0)), name='work_order_issue_weight_check'),
        ),
        migrations.AddIndex(
            model_name='workorderreceiptline',
            index=models.Index(fields=['tenant', 'order'], name='work_order_receipt_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_g__gt', 0), ('labour_rate__gte', 0), ('list_making_rate__gte', 0)), name='work_order_receipt_values_check'),
        ),
        migrations.AddIndex(
            model_name='workorderpiece',
            index=models.Index(fields=['tenant', 'line'], name='work_order_piece_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderpiece',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_g__gt', 0)), name='work_order_piece_weight_check'),
        ),
    ]
