# Generated by Django 5.2.17 on 2026-10-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_payadjustment_kind'),
        ('manufacturing', '0002_rls'),
        ('parties', '0004_workshop_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='craftsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party'),
        ),
    ]
