# Generated by Django 5.2.17 on 2026-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payadjustment',
            name='kind',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Salary deduction')], max_length=10),
        ),
    ]
