# Generated by Django 5.2.17 on 2026-09-24 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('ledger', '0005_account_commodity'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=60)),
                ('iban', models.CharField(blank=True, max_length=40)),
                ('all_branches', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['currency__code', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='treasury.bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='treasury.bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cash boxes',
                'ordering': ['branch__code', 'currency__code', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('transfer', 'Transfer'), ('exchange', 'Currency exchange'), ('card_settlement', 'Card settlement')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('functional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('needs_receipt', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('dest_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount')),
                ('dest_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox')),
                ('dest_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receive_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount')),
                ('source_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox')),
                ('source_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cardterminal')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant', 'currency'], name='treasury_bank_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccountbranch',
            constraint=models.UniqueConstraint(fields=('tenant', 'bank_account', 'branch'), name='treasury_bank_branch_uniq'),
        ),
        migrations.AddIndex(
            model_name='cardterminal',
            index=models.Index(fields=['tenant', 'branch'], name='treasury_terminal_branch_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardterminal',
            constraint=models.CheckConstraint(condition=models.Q(('fee_rate__gte', 0), ('fee_rate__lt', 1)), name='treasury_terminal_fee_range_check'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['tenant', 'branch'], name='treasury_box_branch_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'branch', 'currency'), name='treasury_box_default_uniq'),
        ),
        migrations.AddIndex(
            model_name='treasurydocument',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='treasury_doc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurydocument',
            index=models.Index(condition=models.Q(('needs_receipt', True), ('received_at__isnull', True)), fields=['tenant', 'to_branch'], name='treasury_doc_to_branch_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasurydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='treasury_treasurydocument_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='treasurydocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_bank__isnull', True), ('source_box__isnull', False), ('source_terminal__isnull', True)), models.Q(('source_bank__isnull', False), ('source_box__isnull', True), ('source_terminal__isnull', True)), models.Q(('source_bank__isnull', True), ('source_box__isnull', True), ('source_terminal__isnull', False)), _connector='OR'), name='treasury_doc_one_source_check'),
        ),
        migrations.AddConstraint(
            model_name='treasurydocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dest_bank__isnull', True), ('dest_box__isnull', False)), models.Q(('dest_bank__isnull', False), ('dest_box__isnull', True)), _connector='OR'), name='treasury_doc_one_dest_check'),
        ),
        migrations.AddConstraint(
            model_name='treasurydocument',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('dest_amount__gt', 0), ('fee_amount__gte', 0)), name='treasury_doc_amounts_check'),
        ),
    ]
