# Generated by Django 5.2.17 on 2026-09-24 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('ledger', '0004_metal_position_account'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('parties', '0002_rls'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Cancelled')], default='draft', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('legacy_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('receipt', 'Money received'), ('payment', 'Money paid'), ('metal_in', 'Gold received'), ('metal_out', 'Gold given'), ('conversion', 'Gold balance settled in money')], max_length=12)),
                ('side', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('card', 'Card')], max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('functional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('fine_weight_g', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('direction', models.CharField(blank=True, choices=[('we_owe_gold', 'We owe them gold: pay it in money instead'), ('they_owe_gold', 'They owe us gold: they pay money instead')], max_length=16)),
                ('price_per_fine_g', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'branch', '-business_date'], name='settlement_date_idx'), models.Index(fields=['tenant', 'party'], name='settlement_party_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='settlements_settlement_number_uniq')],
            },
        ),
    ]
