# Generated by Django 5.2.17 on 2026-09-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_settlement_bank_account_settlement_cash_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='side',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('trade_account', 'Trade account')], max_length=16),
        ),
    ]
