# Generated by Django 5.2.17 on 2026-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0004_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='side',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('trade_account', 'Trade account'), ('workshop', 'Workshop')], max_length=16),
        ),
    ]
