# Generated by Django 5.2.17 on 2026-09-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_metal_position_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.commodity'),
        ),
    ]
