# Generated by Django 5.2.17 on 2026-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_account_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open for posting'), ('closed', 'Closed')], default='open', max_length=8),
        ),
    ]
