# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_commissions_account'),
        ('tenants', '0006_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('opening', 'Opening balance'), ('reversal', 'Reversal'), ('closing', 'Year-end closing')], max_length=10),
        ),
        migrations.CreateModel(
            name='PeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('closed', 'Month closed'), ('reopened', 'Month reopened'), ('year_closed', 'Year closed'), ('year_reopened', 'Year reopened')], max_length=16)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-at'], name='ledger_period_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='YearEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reopened_at__isnull', True)), fields=('tenant', 'year'), name='ledger_year_end_open_uniq')],
            },
        ),
    ]
