# Generated by Django 5.2.17 on 2026-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='country',
            field=models.CharField(default='EG', max_length=2),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='locale',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=8),
        ),
    ]
