# Generated by Django 5.2.17 on 2026-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='accent',
            field=models.CharField(default='gold', max_length=16),
        ),
    ]
