# Generated by Django 5.2.17 on 2026-10-03 14:25

import apps.core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='logo',
            field=models.FileField(blank=True, upload_to=apps.core.media.TenantUploadPath('branding'), validators=[apps.core.media.validate_image]),
        ),
    ]
