# Generated by Django 5.2.17 on 2026-10-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='handles_diamonds',
        ),
    ]
