# Generated by Django 5.2.17 on 2026-10-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_tenant_fk_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('I', 'added'), ('U', 'changed'), ('D', 'deleted')], max_length=1),
        ),
    ]
