# Generated by Django 5.2.17 on 2026-09-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('depth', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('product_family', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('watch', 'Watch'), ('beads', 'Beads'), ('stainless', 'Stainless'), ('bullion_coin', 'Bullion Coin'), ('diamond', 'Diamond'), ('stone', 'Stone'), ('other', 'Other')], max_length=16)),
                ('tracking', models.CharField(choices=[('serialized', 'Serialized'), ('bulk', 'Bulk')], max_length=16)),
                ('barcode_prefix', models.PositiveIntegerField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('reorder_min_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('reorder_max_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.itemcategory')),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMakingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_rate_per_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('list_rate_per_g', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='making_charges', to='catalog.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Karat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveSmallIntegerField()),
                ('fineness', models.DecimalField(decimal_places=3, max_digits=7)),
                ('is_reference', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=40)),
                ('legacy_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['metal__code', '-code'],
            },
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='default_karat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.karat'),
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=16)),
                ('name', models.CharField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='karat',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karats', to='catalog.metal'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_currency_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{3}$')), name='catalog_currency_iso_code_check'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('minor_units__lte', 4)), name='catalog_currency_minor_units_max_check'),
        ),
        migrations.AddConstraint(
            model_name='categorymakingcharge',
            constraint=models.UniqueConstraint(fields=('tenant', 'category', 'currency'), name='catalog_categorymakingcharge_uniq'),
        ),
        migrations.AddConstraint(
            model_name='categorymakingcharge',
            constraint=models.CheckConstraint(condition=models.Q(('cost_rate_per_g__gte', 0), ('list_rate_per_g__gte', 0)), name='catalog_categorymakingcharge_non_negative_check'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant', 'parent'], name='catalog_itemcat_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_itemcategory_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode_prefix'), name='catalog_itemcategory_barcode_prefix_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 1), ('depth__lte', 3)), name='catalog_itemcategory_depth_range_check'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 1)), name='catalog_itemcategory_commission_rate_check'),
        ),
        migrations.AddConstraint(
            model_name='metal',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_metal_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='karat',
            constraint=models.UniqueConstraint(fields=('tenant', 'metal', 'code'), name='catalog_karat_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='karat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('tenant', 'metal'), name='catalog_karat_one_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='karat',
            constraint=models.CheckConstraint(condition=models.Q(('fineness__gt', 0), ('fineness__lte', 1000)), name='catalog_karat_fineness_range_check'),
        ),
    ]
