# Generated by Django 5.2.17 on 2026-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='product_family',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('watch', 'Watches'), ('beads', 'Beads'), ('stainless', 'Stainless steel'), ('bullion_coin', 'Bullion and coins'), ('diamond', 'Diamonds'), ('stone', 'Stones'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='tracking',
            field=models.CharField(choices=[('serialized', 'Per piece'), ('bulk', 'By weight')], max_length=16),
        ),
    ]
