# Generated by Django 5.2.17 on 2026-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_itemcategory_product_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='karat',
            name='display_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
