# Generated by Django 5.2.17 on 2026-09-24 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_clear_seeded_names'),
        ('expenses', '0001_initial'),
        ('ledger', '0005_account_commodity'),
        ('org', '0003_tenantprofile_country_alter_tenantprofile_locale'),
        ('tenants', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensevoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.branch'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='tenant',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='expenses_category_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='expensevoucher',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expensevoucher',
            index=models.Index(fields=['tenant', 'category'], name='expense_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensevoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('tenant', 'number'), name='expenses_expensevoucher_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='expensevoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank_account__isnull', True), ('cash_box__isnull', False)), models.Q(('bank_account__isnull', False), ('cash_box__isnull', True)), _connector='OR'), name='expenses_voucher_one_source_check'),
        ),
        migrations.AddConstraint(
            model_name='expensevoucher',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expenses_voucher_amount_check'),
        ),
    ]
