# Generated by Django 5.2.17 on 2026-10-06 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('started_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField()),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('jobs_failed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('dedupe_key', models.CharField(blank=True, max_length=100)),
                ('last_error', models.TextField(blank=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status', 'queued')), fields=['run_at', 'id'], name='jobs_job_due_idx'), models.Index(fields=['status', 'created_at'], name='jobs_job_status_idx'), models.Index(fields=['tenant', 'created_at'], name='jobs_job_tenant_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('name', 'tenant', 'dedupe_key'), name='jobs_job_dedupe_uniq', nulls_distinct=False)],
            },
        ),
    ]
